In [1]:
import tensorflow as tf

In [5]:
A=tf.constant([[1,2],[3,4]],dtype='float32')
B=tf.constant([[5,6],[7,8]],dtype='float32')

In [13]:
add_result=tf.add(A,B);
sub_result=tf.subtract(A,B);
mul_result=tf.multiply(A,B);
div_result=tf.divide(A,B);
matmul_result=tf.matmul(A,B);

In [15]:
print("Addition:\n", + add_result.numpy());
print("Subtraction:\n", + sub_result.numpy());
print("Multiplication:\n", + mul_result.numpy());
print("Division:\n", + div_result.numpy());
print("Matrixmultiplication:\n", matmul_result.numpy());

Addition:
 [[ 6.  8.]
 [10. 12.]]
Subtraction:
 [[-4. -4.]
 [-4. -4.]]
Multiplication:
 [[ 5. 12.]
 [21. 32.]]
Division:
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]
Matrixmultiplication:
 [[19. 22.]
 [43. 50.]]
