In [1]:
import tensorflow as tf

In [3]:
data=tf.constant([[[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]]],dtype='float32')

In [17]:
print("Original Tensor:\n", data.numpy())

Original Tensor:
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]]


In [27]:
splits = tf.split(data,[1,2], axis=1)

print("\nSplit Parts:")
for part in splits:
    print(part.numpy())



Split Parts:
[[[1. 2. 3. 4.]]]
[[[ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]]


In [29]:
merged=tf.concat(splits, axis=1)
print("Merged Tensor:\n", merged.numpy())

Merged Tensor:
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]]


In [31]:
mean_val=tf.reduce_mean(data)
max_val=tf.reduce_max(data)
min_val=tf.reduce_min(data)
sum_val=tf.reduce_sum(data)
std_val=tf.math.reduce_std(data)

In [ ]:
print("statistics:\n")
print(f"Mean:{mean_val.numpy()}")
print(f"Max:{max_val.numpy()}")
print(f"Min:{min_val.numpy()}")
print(f"Sum:{sum_val.numpy()}")
print(