In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [10]:
df=pd.read_csv("iris.csv")

In [12]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
x=df.iloc[:, 0:2].values
y=df.iloc[:, -1].values

In [50]:
x

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [52]:
y

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [14]:
y_binary=np.where(y=='iris_setosa', 1.0, 0.0)

In [54]:
y_binary

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
X=(x-x.mean(axis=0))/x.std(axis=0)

In [56]:
X

array([[-0.90068117,  1.01900435],
       [-1.14301691, -0.13197948],
       [-1.38535265,  0.32841405],
       [-1.50652052,  0.09821729],
       [-1.02184904,  1.24920112],
       [-0.53717756,  1.93979142],
       [-1.50652052,  0.78880759],
       [-1.02184904,  0.78880759],
       [-1.74885626, -0.36217625],
       [-1.14301691,  0.09821729],
       [-0.53717756,  1.47939788],
       [-1.26418478,  0.78880759],
       [-1.26418478, -0.13197948],
       [-1.87002413, -0.13197948],
       [-0.05250608,  2.16998818],
       [-0.17367395,  3.09077525],
       [-0.53717756,  1.93979142],
       [-0.90068117,  1.01900435],
       [-0.17367395,  1.70959465],
       [-0.90068117,  1.70959465],
       [-0.53717756,  0.78880759],
       [-0.90068117,  1.47939788],
       [-1.50652052,  1.24920112],
       [-0.90068117,  0.55861082],
       [-1.26418478,  0.78880759],
       [-1.02184904, -0.13197948],
       [-1.02184904,  0.78880759],
       [-0.7795133 ,  1.01900435],
       [-0.7795133 ,

In [18]:
x_tf=tf.constant(X, dtype='float32')

In [58]:
x_tf

<tf.Tensor: shape=(150, 2), dtype=float32, numpy=
array([[-0.9006812 ,  1.0190043 ],
       [-1.1430169 , -0.13197948],
       [-1.3853526 ,  0.32841405],
       [-1.5065205 ,  0.09821729],
       [-1.021849  ,  1.249201  ],
       [-0.53717756,  1.9397914 ],
       [-1.5065205 ,  0.7888076 ],
       [-1.021849  ,  0.7888076 ],
       [-1.7488563 , -0.36217624],
       [-1.1430169 ,  0.09821729],
       [-0.53717756,  1.4793979 ],
       [-1.2641848 ,  0.7888076 ],
       [-1.2641848 , -0.13197948],
       [-1.8700241 , -0.13197948],
       [-0.05250608,  2.1699882 ],
       [-0.17367394,  3.0907753 ],
       [-0.53717756,  1.9397914 ],
       [-0.9006812 ,  1.0190043 ],
       [-0.17367394,  1.7095946 ],
       [-0.9006812 ,  1.7095946 ],
       [-0.53717756,  0.7888076 ],
       [-0.9006812 ,  1.4793979 ],
       [-1.5065205 ,  1.249201  ],
       [-0.9006812 ,  0.5586108 ],
       [-1.2641848 ,  0.7888076 ],
       [-1.021849  , -0.13197948],
       [-1.021849  ,  0.7888076 ],
     

In [24]:
w=tf.constant([[1.0],
               [-1.0]], dtype='float32')
b=tf.constant([0.2], dtype='float32')

In [60]:
w

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 1.],
       [-1.]], dtype=float32)>

In [62]:
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2], dtype=float32)>

In [32]:
z=tf.matmul(x_tf, w)+b

In [64]:
z

<tf.Tensor: shape=(150, 1), dtype=float32, numpy=
array([[-1.7196856 ],
       [-0.8110375 ],
       [-1.5137666 ],
       [-1.4047377 ],
       [-2.07105   ],
       [-2.276969  ],
       [-2.095328  ],
       [-1.6106565 ],
       [-1.1866801 ],
       [-1.0412341 ],
       [-1.8165753 ],
       [-1.8529923 ],
       [-0.9322054 ],
       [-1.5380446 ],
       [-2.022494  ],
       [-3.064449  ],
       [-2.276969  ],
       [-1.7196856 ],
       [-1.6832685 ],
       [-2.4102757 ],
       [-1.1259851 ],
       [-2.180079  ],
       [-2.5557215 ],
       [-1.2592919 ],
       [-1.8529923 ],
       [-0.6898696 ],
       [-1.6106565 ],
       [-1.5985177 ],
       [-1.3683208 ],
       [-1.5137666 ],
       [-1.162402  ],
       [-1.1259851 ],
       [-2.9796982 ],
       [-2.8463914 ],
       [-1.0412341 ],
       [-1.1502631 ],
       [-1.235014  ],
       [-2.192218  ],
       [-1.4168768 ],
       [-1.4894887 ],
       [-1.8408535 ],
       [ 0.3156684 ],
       [-1.8772702 ],
    

In [36]:
y_pred_step=(z>=0, 'int 32')

In [38]:
y_pred_sigmoid=tf.math.sigmoid(z)

In [48]:
print("first 10 True labels (Setosa=1, others=0):", y_binary[:10])
print("first 10 step outputs:", y_pred_step [:10])
print("first 10 sigmoid probabilities:", y_pred_sigmoid [:10])

first 10 True labels (Setosa=1, others=0): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
first 10 step outputs: (<tf.Tensor: shape=(150, 1), dtype=bool, numpy=
array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
      